### ISSUE TITLE
Cant add, remove, load recipes. Cant even remove other default scripts without returning back on reload or restart

### ISSUE THREAD

**Issue by calypsocz** [Wurmcraft/WurmTweaks2#27]
Hey. When I wanna to make a custom recipe, all scripts are rewritten to default state. Even those ones with default generation are not able to be deleted without returning back after reload or game restart. Hope to speak with u soon.

**Comment by Wurmatron** [comment]
Im amussing you are not changing the 
`S:masterScript=https://raw.githubusercontent.com/Wurmcraft/WurmTweaks2/Rewrite/examples/master.w`
and it's deleting your scripts because its syncing with the default ones.

Checkout https://github.com/Wurmcraft/Survival-of-the-Ages/tree/master/scripts or just make sure 
`checkForUpdates=false`

**Comment by Wurmatron** [comment]
This system makes it so you can update recipes without having to update the modpack / scripts because they sync with a "database" aka a web server

**Comment by Wurmatron** [comment]
Feel free to joni my discord if you still need help https://www.wurmcraft.com/
